In [1]:
print('hello everyone today we will learn about RANDOM FORREST')

hello everyone today we will learn about RANDOM FORREST

In [2]:
!pip install pandas
!pip install scikit-learn
!pip install matplotlib
!pip install seaborn
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [3]:
import pandas as pd
from sklearn import tree
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (accuracy_score,
                             precision_score,
                             confusion_matrix,
                             ConfusionMatrixDisplay)
import matplotlib.pyplot as plt

In [8]:
data = pd.read_csv('FC_Barcelona_Statistics.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Date                            200 non-null    object
 1   Opponent                        200 non-null    object
 2   Home/Away                       200 non-null    object
 3   Competition                     200 non-null    object
 4   Goals Scored                    200 non-null    int64
 5   Goals Conceded                  200 non-null    int64
 6   Possession (%)                  200 non-null    int64
 7   Shots on Target                 200 non-null    int64
 8   xG                              200 non-null    float64
 9   Pass Accuracy (%)               200 non-null    int64
 10  Tackles Won                     200 non-null    int64
 11  Key Passes                      200 non-null    int64
 12  Result                          200 non-null    object
 13  Injury Impact (%)               200 non-null    int64
 14  Rest Days Before Match          200 non-null    int64
 15  Opponent Strength (ELO Rating)  200 non-null    int64
 16  Weather Conditions              200 non-null    object
 17  Managerial Change (Yes/No)      200 non-null    object
dtypes: float64(1), int64(10), object(7)
memory usage: 28.3+ KB

In [9]:
data.isna().sum()

Date                              0
Opponent                          0
Home/Away                         0
Competition                       0
Goals Scored                      0
Goals Conceded                    0
Possession (%)                    0
Shots on Target                   0
xG                                0
Pass Accuracy (%)                 0
Tackles Won                       0
Key Passes                        0
Result                            0
Injury Impact (%)                 0
Rest Days Before Match            0
Opponent Strength (ELO Rating)    0
Weather Conditions                0
Managerial Change (Yes/No)        0
dtype: int64

In [13]:
label_encoder = LabelEncoder()
data['Encoded_Home/Away'] = label_encoder.fit_transform(data['Home/Away'])
data['Encoded_Opponent'] = label_encoder.fit_transform(data['Opponent'])
data['Encoded_Managerial_Change_(Yes/No)'] = label_encoder.fit_transform(data['Managerial Change (Yes/No)'])
data['Encoded_Result'] = label_encoder.fit_transform(data['Result'])
data['Encoded_Competition'] = label_encoder.fit_transform(data['Competition'])

In [12]:
data

           Date  ... Encoded_Result
0    01-01-2020  ...              1
1    11-01-2020  ...              0
2    21-01-2020  ...              0
3    25-01-2020  ...              0
4    28-01-2020  ...              1
..          ...  ...            ...
195  10-08-2024  ...              0
196  06-09-2024  ...              0
197  26-09-2024  ...              1
198  12-10-2024  ...              1
199  25-03-2025  ...              1

[200 rows x 22 columns]

In [15]:
data.drop(['Home/Away', 'Opponent', 'Managerial Change (Yes/No)', 'Result',
           'Competition', 'Pass Accuracy (%)',
'Tackles Won', 'Goals Scored', 'Goals Conceded', 'Possession (%)', 'Shots on Target',
'xG', 'Key Passes' , 'Weather Conditions'], axis=1, inplace=True)

In [16]:
data

           Date  Injury Impact (%)  ...  Encoded_Result  Encoded_Competition
0    01-01-2020                 23  ...               1                    1
1    11-01-2020                  0  ...               0                    1
2    21-01-2020                 17  ...               0                    2
3    25-01-2020                 25  ...               0                    2
4    28-01-2020                 10  ...               1                    0
..          ...                ...  ...             ...                  ...
195  10-08-2024                  6  ...               0                    2
196  06-09-2024                 22  ...               0                    1
197  26-09-2024                 24  ...               1                    1
198  12-10-2024                 21  ...               1                    1
199  25-03-2025                 15  ...               1                    1

[200 rows x 9 columns]

In [18]:
data.drop('Date', axis=1, inplace=True)

In [19]:
X= data.drop('Encoded_Result', axis=1)
y= data['Encoded_Result']

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
randomForrestModel = RandomForestClassifier(n_estimators=300, random_state=42)
randomForrestModel.fit(X_train, y_train)

RandomForestClassifier(n_estimators=300, random_state=42)

In [25]:
predict = randomForrestModel.predict(X_test)

In [26]:
accuracy = accuracy_score(y_test, predict)
print("Accuracy: ", accuracy)

Accuracy:  0.55